@startuml
skinparam monochrome true
skinparam BoxPadding 5
header Ports and Adapter POC
title Create Async Report Use Case

hide footbox
actor HttpClient as user << User >>

box "REST Application" #FBFBFB
 participant "RestApi" as api << API >>
end box

autonumber
user ->(5) api: Post[ReportRequest]
api --> user : (Accepted 'Content-Location')
@enduml