@startuml
:dependency-file;
:read-line-producer;
:line-topic|
:line-consumer;
:parse line]
if (isValid?) equals (no) then
  :invalid-dependency-topic|
  :invalid-dependency-consumer;
  :process-invalid-dependency]
  stop
else
  :valid-dependency-topic|
  :valid-dependency-consumer;
  :check-remote-dependency]
  if (hasNewVersion?) equals (no) then
    :latest-dependency-topic|
    :latest-dependency-consumer;
    :process-latest-dependency]
    stop
  else
    :upgraded-dependency-topic|
    :upgraded-dependency-consumer;
    :process-upgraded-dependency]
    stop
  endif  
  
endif



@enduml
