name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [ opened ]

jobs:

  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'sbt'      
      - name: compile
        run: sbt -v compile
      - name: tests
        run: sbt test
      - name: tests with coverage
        run: sbt xcoverage
      - name: upload coverage reports to codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}        
      - name: assembly
        run: sbt assembly
      - name: dependency updates
        run: sbt xdup
            
