name: Dependency Analyzer CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [ opened ]

jobs:

  build:

    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1
        with:
          jvm: zulu@20
      - name: compile main
        run: sbt -v --client compile
        working-directory: ${{env.WORK_DIR}}
      - name: compile unit tests
        run: sbt -v --client Test/compile
        working-directory: ${{env.WORK_DIR}}
      - name: compile integration tests
        run: sbt -v --client integration/Test/compile
        working-directory: ${{env.WORK_DIR}}
      - name: application tests
        run: sbt xcoverage
        working-directory: ${{env.WORK_DIR}}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}        
      - name: integration tests
        run: sbt -v --client integration/test
        working-directory: ${{env.WORK_DIR}}
      - name: assembly
        run: sbt -v --client assembly
        working-directory: ${{env.WORK_DIR}}
