name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [ opened ]

jobs:

  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1
        with:
          jvm: zulu@21
      - name: compile
        run: sbt -v compile
      - name: tests
        run: sbt test

  coverage:
    needs: test
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1
        with:
          jvm: zulu@20
      - name: tests with coverage
        run: sbt xcoverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}        
          

  dependency-updates:
    needs: test
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/setup-action@v1
        with:
          jvm: zulu@20
      - name: dependency updates
        run: sbt xdup
      
  assembly:
    needs: test
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1
        with:
          jvm: zulu@20
      - name: assembly
        run: sbt assembly
            
